swagger: '2.0'
info:
    $ref: ./info/index.yaml
paths:
  /foo:
    get:
      responses:
        200:
          description: OK
  /bar:
    get:
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/User'
definitions:
  User:
    type: object
    properties:
      name:
        type: string
