name: Sync to ReadMe
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gkoberger/github-readme-sync@master
        with:
          readme-oas-key: ${{ secrets.README_OAS_KEY }}

          # [OPTIONAL CONFIG]
          # These are optional, don't use unless you need to!

          # oas-file-path: './swagger.json'
          # api-version: 'v1.0.0'
